backend:
  name: test-repo

media_folder: static/assets
public_folder: /assets

collections:
  - name: nonogram
    label: Nonograms
    folder: Nonogram
    create: true
    fields:
      - { name: name, label: Name }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
